### PR TITLE
Feat/lint

### PR DESCRIPTION
**Pull request by ArmanA30**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes #(issue)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Open an issue for bug report or feature request and mention it to this PR.
- [x] The commit message follows our guidelines: <https://github.com/AliMD/alwatr/blob/main/CONTRIBUTING.md#commit-message-format>
- [x] All methods have proper description in `jsdocs` format with `@example` section.
- [x] Docs have been added / updated (for bug fixes / features).
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Review by MM25Zamanian — APPROVED** [review]
@AliMD Ok?

**Review by AliMD — APPROVED** [review]
thanks

**Comment by AliMD** [comment]
خطا بیلد!

**Comment by AliMD** [comment]
چه باگ احمقانه ای!
بیلد موقع نصب لینت رو چک میکنه!

**Comment by AliMD** [comment]
Now its ok #7

**Pull request merged**
